### ISSUE TITLE
Question about combination with Instagib mutator

### ISSUE THREAD

**Issue by bjb43** [alexstrout/foxWSFix-UT2k4#5] opened 2021-05-15 12:49 UTC
Hi, first thanks a lot for your great work! It runs great, however, when I use the Instagib mutator, the shock rifle isn't properly placed as expected (your mod works fine without it though). Is this something you can reproduce?

I'm running the native linux client.

Thanks a lot!

PS: Funny behaviour: It seems with every map change (bot match, after one game finishes) the weapon moves further to the right/left/front (depending on the setting)... I can provide screenshots if required.

**Comment by alexstrout** [comment] 2021-06-11 23:39
Thanks for the report! Respawning is actually a [special case for weapon positioning](https://github.com/alexstrout/foxWSFix-UT2k4/blob/master/Classes/foxPlayerInput.uc#L105-L109), and I bet it's not quite catching whatever's going on in Instagib. I'll take a look! I'm overdue for a UT session anyway.

As for the funny behavior, that is an interesting bug :)

**Comment by bjb43** [comment] 2021-06-12 19:56
Thanks a lot for looking into this. Just to clarify on my side: Respawning within a match doesn't do anything funny, it is once a (bot) match (instant action) is finished and the next map has loaded, that one starts with a slightly more displaced shock rifle... and this goes on and on, thus after a few couple matches, the weapon is quite displaced. Very interesting behaviour...

So thanks a lot for taking a look!

**Comment by alexstrout** [comment] 2021-06-24 22:53
I looked into this, but unfortunately couldn't reproduce either issue with Instagib rifles or displaced weapons after matches.

Are you per chance using an ultra-wide setup? I'm wondering if this gets amplified the wider you go. Also out of curiosity, how many matches did you go before you started noticing issues? Thanks!

**Comment by Doridian** [comment] 2021-06-24 22:59
I would like to add my experience to this thread. I experienced the same issue.
My setup is ultrawide (3840x1600). It takes me about 3-4 matches until I clearly see parts of the super shock rifle I'm not supposed to see and it looks very much off.

**Comment by alexstrout** [comment] 2021-06-25 00:06
Nice, thanks for the input - I'll take a look!

**Comment by Doridian** [comment] 2021-06-25 04:12
Match 1
![1](https://user-images.githubusercontent.com/631409/123368554-dc885200-d530-11eb-92ea-3f16ecee978d.jpg)

Match 2
![2](https://user-images.githubusercontent.com/631409/123368566-e1e59c80-d530-11eb-894a-80d459f3efd7.jpg)

Match 3
![3](https://user-images.githubusercontent.com/631409/123368569-e4e08d00-d530-11eb-841d-1ac55038c730.jpg)

Match 4
![4](https://user-images.githubusercontent.com/631409/123368584-e90caa80-d530-11eb-9206-29b053f7cb95.jpg)

Match 5
![5](https://user-images.githubusercontent.com/631409/123368589-ed38c800-d530-11eb-808e-0f0444f48b57.jpg)

**Comment by bjb43** [comment] 2021-06-25 19:03
Looks the same for me, however I'm only using a full HD setup (1920*1080); if it helps: I'm on Linux using openGL. Thanks a lot for investigating!!!

**Comment by alexstrout** [comment] 2021-06-26 13:30
Thank you both for the screenshots & extra info - I found the issue and it should be resolved with v2.1.2. Let me know if you still have any issues!

**Comment by bjb43** [comment] 2021-06-27 11:48
Thanks so much, it is working now for me :)

**Comment by alexstrout** [comment] 2021-10-30 22:28
This should now be properly fixed with v2.2.0 - it turns out this could also happen when exiting to menu.

The info used to prevent scaling your current weapon multiple times (since it has to edit "default" values to be consumed properly by weapon rendering code) is now properly carried over between levels as originally intended. 👍

**Closed by alexstrout** 2021-10-30 22:28 UTC
